# Generated by Django 5.1.4 on 2025-03-29 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_uploadmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.FileField(default='', upload_to='images'),
        ),
    ]
